### ISSUE TITLE
Search text clash in Explore

### ISSUE THREAD

**Issue by nsuberi** [resource-watch/resource-watch#18]
When I type in the search box on explore, the default text doesn't go away, resulting in the input text and default text layering over top of each other.

**Comment by pablopareja** [comment]
Hi @nsuberi, 
Thanks for submitting the issue. We are currently working on a fix for that that will be included in the next deployment.
Cheers

**Comment by pablopareja** [comment]
We've deployed a new version including a fix for this bug.
@nsuberi Could you please confirm that you're not experiencing the problem aforementioned anymore?

**Comment by nsuberi** [comment]
Fixed!

2017-07-03 7:21 GMT-04:00 Pablo Pareja Tobes <notifications@github.com>:

**Comment by pablopareja** [comment]
Cool, closing the issue...
